apiVersion: v1
description: Sentry is a cross-platform crash reporting and aggregation platform.
name: sentry
version: 4.1.0
appVersion: 10.0.0
keywords:
  - debugging
  - logging
sources:
  - https://github.com/getsentry/sentry
home: https://sentry.io/
icon: https://sentry-brand.storage.googleapis.com/sentry-glyph-black.png
