---
apiVersion: v1
kind: Service
metadata:
    name: {{ template "clickhouse.fullname" . }}
    labels:
        app: {{ template "clickhouse.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
{{- if .Values.service.annotations }}
    annotations:
{{ toYaml .Values.service.annotations | indent 8 }}
{{- end }}
spec:
    selector:
        app: {{ template "clickhouse.fullname" . }}
        release: "{{ .Release.Name }}"
    type: {{ .Values.service.type }}
    ports:
        -   name: tcp
            protocol: TCP
            port: 9000
            targetPort: 9000
{{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort.tcp) }}
            nodePort: {{ .Values.service.nodePort.tcp }}
{{- end }}
        -   name: http
            protocol: TCP
            targetPort: 8123
            port: 8123
{{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort.http) }}
            nodePort: {{ .Values.service.nodePort.http }}
{{- end }}
        -   name: node-http
            protocol: TCP
            port: 9009
            targetPort: 9009
{{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort.interserver) }}
            nodePort: {{ .Values.service.nodePort.interserver }}
{{- end }}
{{- if .Values.service.externalIPs }}
    externalIPs:
{{ toYaml .Values.service.externalIPs | indent 8 }}
{{- end }}
