apiVersion: v1
name: traefik
version: 2.0.5
appVersion: 2.2.6
description: A Traefik based Kubernetes ingress controller with Let's Encrypt support
keywords:
- traefik
- ingress
- acme
- letsencrypt
home: https://traefik.io/
sources:
- https://github.com/containous/traefik
- https://github.com/helm/charts/tree/master/stable/traefik
engine: gotpl
icon: https://docs.traefik.io/img/traefik.logo.png
