---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "snuba.fullname" . }}
    labels:
        app: {{ template "snuba.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
spec:
    selector:
        matchLabels:
            app: {{ template "snuba.fullname" . }}
            release: "{{ .Release.Name }}"
    template:
        metadata:
{{- if .Values.annotations }}
            annotations:
{{ toYaml .Values.annotations | indent 16 }}
{{- end }}
            labels:
                app: {{ template "snuba.fullname" . }}
                release: "{{ .Release.Name }}"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 16 }}
{{- end }}

        spec:
{{- if .Values.nodeSelector }}
            nodeSelector:
{{ toYaml .Values.nodeSelector | indent 16 }}
{{- end }}
{{- if .Values.image.imagePullSecrets }}
            imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 16 }}
{{- end }}
            containers:
                -   name: {{ include "snuba.fullname" . }}-api
                    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    ports:
                        - containerPort: 1218
                    env:
{{ include "snuba.environment" . | indent 24 }}
                -   name: {{ include "snuba.fullname" . }}-consumer
                    args:
                        - consumer
                        - --auto-offset-reset=latest
                        - --max-batch-time-ms
                        - '750'
                    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    env:
{{ include "snuba.environment" . | indent 24 }}
                -   name: {{ include "snuba.fullname" . }}-replaces
                    args:
                        - replacer
                        - --auto-offset-reset=latest
                        - --max-batch-size
                        - '3'
                    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    env:
{{ include "snuba.environment" . | indent 24 }}
