---
apiVersion: v1
kind: Service
metadata:
    name: {{ template "snuba.fullname" . }}
    labels:
        app: {{ template "snuba.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
{{- if .Values.service.annotations }}
    annotations:
{{ toYaml .Values.service.annotations | indent 8 }}
{{- end }}
spec:
    selector:
        app: {{ template "snuba.fullname" . }}
        release: "{{ .Release.Name }}"
    type: {{ .Values.service.type }}
    ports:
        -   name: http
            protocol: TCP
            port: 1218
            targetPort: 1218
{{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort.http) }}
            nodePort: {{ .Values.service.nodePort.http }}
{{- end }}
{{- if .Values.service.externalIPs }}
    externalIPs:
{{ toYaml .Values.service.externalIPs | indent 8 }}
{{- end }}
