{{- if .Values.global.minio.enabled -}}
{{- if eq (include "gitlab.ingress.enabled" $) "true" -}}
{{- $minioHostname := include "gitlab.minio.hostname" . -}}
{{- $tlsSecret := include "minio.tlsSecret" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "minio.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
  annotations:
    {{ include "gitlab.certmanager_annotations" . }}
  {{- range $key, $value := merge .Values.ingress.annotations .Values.global.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    - host: {{ $minioHostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "minio.fullname" . }}-svc
              servicePort: {{ .Values.servicePort }}
  {{- if (and $tlsSecret (eq (include "gitlab.ingress.tls.enabled" $) "true" )) }}
  tls:
    - hosts:
      - {{ $minioHostname }}
      secretName: {{ $tlsSecret }}
  {{- else }}
  tls: []
  {{- end }}
{{- end -}}
{{- end -}}
